# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topmenu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing_detail',
            old_name='listing',
            new_name='detail'
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_text',
            new_name='header'
        ),
        migrations.DeleteModel(
            name='Listing_detail',
        ),
    ]
