# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topmenu', '0002_auto_20160528_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='detail',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='header',
            field=models.CharField(max_length=40),
        ),
    ]
