# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topmenu', '0005_auto_20160610_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_sms_quant',
            field=models.PositiveIntegerField(default=1, max_length=4),
        ),
    ]
