# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topmenu', '0007_auto_20160610_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_state',
        ),
        migrations.AddField(
            model_name='user',
            name='user_loc',
            field=models.CharField(default='Los Angeles', max_length=20),
            preserve_default=False,
        ),
    ]
