# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topmenu', '0008_auto_20160711_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
